### ISSUE TITLE
Support for PyTorch (.pt, .pth), Tensorflow (SavedModel )

### ISSUE THREAD

**Issue by jax79sg** [bosch-aisecurity-aishield/watchtower#18]
**Is your feature request related to a problem? Please describe.**
Without going through conversions, can WatchTower support any popular saved version out of the box?

**Describe the solution you'd like**
Support other popular saved formats

**Describe alternatives you've considered**
Perform own conversion, but at the risk of triggering vulnerabilities.

**Additional context**

**Comment by DeepakByrappa** [comment]
This feature is available in Watchtower 1.2
