### ISSUE TITLE
Bring Support for safetensors model framework.

### ISSUE THREAD

**Issue by mauryapankaj** [bosch-aisecurity-aishield/watchtower#21]
**Is your feature request related to a problem? Please describe.**
Not able to scan model saved with safetensors model framework

**Describe the solution you'd like**
bringing support for safetensors model framework will solve the problem.

**Describe alternatives you've considered**

**Additional context**

**Comment by DeepakByrappa** [comment]
This Feature is available in Watchtower 1.2
