### ISSUE TITLE
Huggingface URL parsing 

### ISSUE THREAD

**Issue by mauryapankaj** [bosch-aisecurity-aishield/watchtower#23]
**Is your feature request related to a problem? Please describe.**
parsing of huggingface url support needed. when given repos url containing more in the path, scanning failed. 

**Describe the solution you'd like**
parsing to determine correct huggingface url will solve the issue.

**Describe alternatives you've considered**

**Additional context**

**Comment by DeepakByrappa** [comment]
Feature available in v1.1 Release
