### ISSUE TITLE
[BUG] Security Vulnerability

### ISSUE THREAD

**Issue by mugs-1391** [bosch-aisecurity-aishield/watchtower#28]
Potential issues found with the latest release v1.2. Shared details over email.

**Comment by Avphadke** [comment]
•	worked on enhancements and have addressed this issue in the latest Watchtower release ([Version v1.2.2](https://github.com/bosch-aisecurity-aishield/watchtower/releases/tag/v1.2.2)).
•	In this release, measures were implemented to ensure the safe loading of all file types.
•	To reinforce security, older versions have been deprecated, making Version v1.2.2 the only supported version moving forward.

- Watchtower has always been designed for use in sandboxed environments, and this requirement has been made more explicit in the updated documentation.
