### ISSUE TITLE
Enabling Targeted Code Scanning for GitHub Branches 

### ISSUE THREAD

**Issue by DeepakByrappa** [bosch-aisecurity-aishield/watchtower#5]
The ability to scan a specific branch in a GitHub repository is crucial for maintaining code quality and identifying potential issues in isolated development branches. This feature is particularly useful for teams employing a branching strategy where different features or fixes are developed in separate branches before merging into the main codebase.

**Comment by Avphadke** [comment]
feature available in commit id bdefa31712c1e6295f255bb083fa72681007cd14 and released with V1.0 public release
